server:
  port: 4444

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productcontroller
    username: root
    password: root123
  jpa:
   hibernate:
    ddl-auto: create

  
  application:
    name: product-service

  config:
    import:
    - optional:configserver:http://localhost:8888/

 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka     
  instance:
    prefer-ip-address: true
      
resilience4j:
  retry:
    instances:
      productapi:
       max-attempts: 3
       wait-duration: 20s 
      
      
    